name: Build template PDF
on: push

jobs:
  build_latex_and_md:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: templates.tex
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          add: templates.pdf
          author_name: 'GitHub Action'
          author_email: 'action@github.com'
          message: 'Updating built PDF'
